
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_
/*------------------------*/


#define LOG_CONG_LEVEL_NULLNET LOG_LEVEL_DEBUG

#define ZOUL_CONF_USE_CC1200_RADIO          1
#define IEEE802154_CONF_DEFAULT_CHANNEL     2

/*#undef  NETSTACK_CONF_RADIO
#define NETSTACK_CONF_RADIO         cc1200_driver
#define CC1200_CONF_USE_GPIO2       0
#define CC1200_CONF_USE_RX_WATCHDOG 0
#define ANTENNA_SW_SELECT_DEF_CONF  ANTENNA_SW_SELECT_SUBGHZ

*/
#endif  /* PROJECT_CONF_H_ */

