CONTIKI_PROJECT = MQ131-multigas-client oz-cono2.c oz-structs.c oz-cono3.c 
CONTIKI = ../..


CONTIKI_TARGET_SOURCEFILES += multigas.c dht22.c
CONTIKI_TARGET_SOURCEFILES += MQ131.c

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include

