CONTIKI_PROJECT = mgas-s1 mgas-s2 
CONTIKI = ../..


CONTIKI_TARGET_SOURCEFILES += multigas.c dht22.c pm10-sensor.c adc-sensors.c

MAKE_NET = MAKE_NET_NULLNET
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include

