CONTIKI_PROJECT = gw sta-2.4_2



all: $(CONTIKI_PROJECT)

##MODULES += os/services/shell

#CONTIKI_TARGET_SOURCEFILES += dht22.c multigas.c pm10-sensor.c adc-sensors.c
MAKE_NET = MAKE_NET_NULLNET
CONTIKI = ../..

include $(CONTIKI)/Makefile.include



