CONTIKI_PROJECT = multigas-client multigas-client1 multigas-client2 
CONTIKI = ../..


CONTIKI_TARGET_SOURCEFILES += multigas.c dht22.c pm10-sensor.c adc-sensors.c



all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include

