CONTIKI_PROJECT = mq131-multigas-thingspeak
CONTIKI = ../..

MODULES += os/services/shell
CONTIKI_TARGET_SOURCEFILES += multigas.c
CONTIKI_TARGET_SOURCEFILES += MQ131.c


#TARGET_LIBFILES += -L multigas.c multigas.h

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include

